version: "3.8"
services:
    mlflow-server:
        image: ghcr.io/mlflow/mlflow:latest
        ports:
            - "5000:5000"
        command: mlflow server -h 0.0.0.0 -p 5000
        volumes:
            - mlflow-data:/mlflow

volumes:
    mlflow-data:
