name: "Build Thesis Document for PR"
on: 
  pull_request:
    paths:
      - 'report_thesis/**'
permissions:
    contents: write
    pull-requests: write
defaults:
    run:
        working-directory: report_thesis
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - uses: actions/cache@v3
              name: Tectonic Cache
              with:
                  path: ~/.cache/tectonic
                  key: ${{ runner.os }}-tectonic-${{ hashFiles('**/*.tex') }}
                  restore-keys: |
                      ${{ runner.os }}-tectonic-
            - uses: wtfjoke/setup-tectonic@v2
              with:
                  github-token: ${{ secrets.github_token }}
            - name: Run Tectonic
              run: tectonic -X build
            - name: Upload PDF
              uses: actions/upload-artifact@v2
              with:
                  name: thesis-pdf
                  path: report_thesis/build/thesis/thesis.pdf
            - name: Post comment with PDF link
              uses: actions/github-script@v6
              with:
                  script: |
                    const { data: artifacts } = await github.rest.actions.listWorkflowRunArtifacts({
                      owner: context.repo.owner,
                      repo: context.repo.repo,
                      run_id: context.runId
                    });
                    const artifact = artifacts.artifacts.find(a => a.name === 'thesis-pdf');
                    if (artifact) {
                      const artifactUrl = `${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}/artifacts/${artifact.id}`;
                      const comment = `Built PDF for this PR: [Download PDF](${artifactUrl})`;
                      await github.rest.issues.createComment({
                        ...context.repo,
                        issue_number: context.issue.number,
                        body: comment
                      });
                    } else {
                      const comment = `Artifact 'thesis-pdf' not found.`;
                      await github.rest.issues.createComment({
                        ...context.repo,
                        issue_number: context.issue.number,
                        body: comment
                      });
                    }
                  github-token: ${{ secrets.GITHUB_TOKEN }}
